-- Disable RLS on tables for development/testing
-- Run this in Supabase SQL Editor if you don't have the service role key yet

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE trades DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock_trades DISABLE ROW LEVEL SECURITY;
ALTER TABLE option_trades DISABLE ROW LEVEL SECURITY;
ALTER TABLE option_legs DISABLE ROW LEVEL SECURITY;
ALTER TABLE news_articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock_setups DISABLE ROW LEVEL SECURITY;
ALTER TABLE auth_logs DISABLE ROW LEVEL SECURITY;

-- After testing is complete, re-enable RLS with:
-- ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE trades ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE stock_trades ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE option_trades ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE option_legs ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE news_articles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE stock_setups ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE auth_logs ENABLE ROW LEVEL SECURITY;
